### ISSUE TITLE
Possible to have group leader sign up members?

### ISSUE THREAD

**Issue by ghost** [mintunmedia/groups-for-membermouse#17]
I would like to know if it is possible to set up the addon so that the Group Leader is able to sign-up new members to the group.
At the moment, the group leader has to copy the sign-up form link and send it to new members so that they sign-up themselves. The group leader is not able to access the sign-up form because he/she is logged in.
I would like to find a way in which the group leader, while logged in, could access the sign-up form and register new members independently.
Thank you

**Comment by mattmintun** [comment]
This is great feedback, thanks! The Group Leader has access to a "Leader Dashboard" that will allow them to manage their group - adding and removing members as needed based on the number of seats you've provided to their group. 

This dashboard was originally developed to be in the /wp-admin/ area of the site, which is not desired, so we're working on implementing this dashboard into a shortcode that you can easily add to any page of your site. 

We're looking to release a new update that will fix many of the issues this plugin has had over the past few years before we took it over in the next 2 weeks. Then we'll be implementing this Leader Dashboard shortcode. Look out for it in the beginning of Q3 2018! We'll post an update to the Repository here!
