### ISSUE TITLE
Sign Up Link for creating user not inserting record of user in  wp_group_sets_members table

### ISSUE THREAD

**Issue by Sonal824** [mintunmedia/groups-for-membermouse#4]
hey , after creating signup link from Group Management Dashboard and registering it then it only add records in wp_users table but not inserting record in wp_group_sets_members  and because of that i am not able to see member in Group Management Dashboard.

how can i resolve this ?

**Comment by Sonal824** [comment]
ok.. i resolved it by including cf_2 (custom field) as hidden type in my form following is code.

[MM_Form_Field type='custom-hidden' id='2']

**Comment by WolfieZero** [comment]
Bringing this up after a while, I'm still having this issue and that assigns the user as in a group but doesn't assign them to a group. It works if I manually assign them in the admin panel, but for current users using the checkout link it won't.

**Comment by roymckenzie** [comment]
@WolfieZero I recently pushed an update to the code base that should fix this. If you have a moment and can confirm the latest master does, that would be great.

**Comment by mattmintun** [comment]
Hey there, if this is still an issue with our most recent release, please let us know and we'll look into it!
