### ISSUE TITLE
Free seats for Paid groups? (Paypal)

### ISSUE THREAD

**Issue by bezoris** [mintunmedia/groups-for-membermouse#5]
Pasting my longish post from the MM forum, but has anyone been able to get this working recently?
Many thanks.

---

So, I was able to hack this a little bit and essentially do what I need - but it's not ideal. There's also an issue with my use case that seems to be primarily Paypal related.

Short version: I have paid groups that include free seats (Family, Classroom plans, etc). Still can't get the shortcode/dashboard going (won't display), but I was able to create raw links from Products for seats...

However, Paypal kicks up the following strange error:

Invalid Regular period. You must specify valid values for the A3, P3, and T3 parameters for a subscription

After fiddling around (and two call to Paypal Dev Int), it appears that Paypal does not support completely Free subscriptions (even though they're tied to a paid Group plan). Bummer... as I was obviously looking for (younger) students to be able to easily join a subscription purchased by a teacher by simply clicking a button.

Once I changed the Seat price to $0.01, everything functions. Paypal strongly agreed with my scenario and said they would escalate this functionality, for what it's worth. But, still, it now requires each "free" seat to pay at least a penny for access. Not ideal. (And, yes, I asked about workarounds, like an instant discount or charge-back... no haps as of yet).

Am I missing something here? Welcome any suggestion about possible solutions, but for now, while it's a bit ugly, it works.

On a side note, has anyone been able to get the Dataview/Dashboard going?

Best, Chris.

**Comment by bezoris** [comment]
Is this still being developed?

**Comment by membermouse** [comment]
This is not an active project for the MemberMouse product team.

**Comment by glacier890** [comment]
This obviously isn't ideal, but here's how I am working around the issue.  I have the group members sign up for the free membership level - nothing to do with the group initially.  I then gave group leaders the ability to invite users to their group - I copied the code from edit_group.php and pasted it into manage group php(you have to change the variable to $gid when passing into the ajax function). After the group leader has the ability to add free members to their group. I then had to write multiple calls to the database to store the membership level of the group leader into a variable, and then change the membership level of the group member from their free account to the membership level of the group leader. I can go over that more if anybody is interested. There is a few other pieces to clean up from there but that's my overall plan to make it work.

**Comment by colppena** [comment]
I was wondering if anyone found an easy solution for this Free seats for Paid groups. I am planning to implement but using stripe. Any suggestion is highly appreciate it

**Comment by roymckenzie** [comment]
Is there still interest in this functionality? If so we can consider adding it to the roadmap.
