### ISSUE TITLE
'This member doesn't exist' error message

### ISSUE THREAD

**Issue by buckeyeclyde** [mintunmedia/groups-for-membermouse#6]
Manually adding a member to an existing group fails with 'This member doesn't exist' no matter what user's email or username you put in. The related code is in the MemberMouseGroupAddon plugin, includes/create_group_leader.php starting at line 19.

$userSql = "SELECT ID FROM ".$wpdb -> prefix."users WHERE user_email = '".$user."' OR user_login = '".$user."'";

So it's looking for users based on email or login, I'm not sure what the issue is.

(Side note, automatic group creation via the signup form does create a new group but doesn't assign the user as a group leader. Maybe related, though this doesn't have to be fixed.)

**Comment by roymckenzie** [comment]
@buckeyeclyde was the user an existing WordPress member? Sorry for the late response.
