### ISSUE TITLE
Edit Group and Cancel Group not working

### ISSUE THREAD

**Issue by Alanv1** [mintunmedia/groups-for-membermouse#7]
For some reason the Edit Group and Cancel Group buttons are not working on the user or admin side. I have tried downloading and reinstalling with no luck. Any thoughts...?

**Comment by roymckenzie** [comment]
@Alanv1 were you able to resolve this? Sorry for the late response.

**Comment by mattmintun** [comment]
We've resolved this in the most recent release. Check it out!
