### ISSUE TITLE
403 Error when attempting Create Group

### ISSUE THREAD

**Issue by danielleoverman** [mintunmedia/groups-for-membermouse#9]
Failed to load resource: the server responded with a status of 403 ()
.../wp-content/plugins/MemberMouseGroupAddon/includes/create_group.php

The page at '.../wp-admin/admin.php?page=membermousegroupaddon' was loaded over HTTPS, but requested an insecure script '.../wp-content/plugins/MemberMouseGroupAddon/js/mm-group-import_wizard.js?ver=1.0.0'. This content should also be served over HTTPS.

**Comment by roymckenzie** [comment]
@danielleoverman 

1. Regarding the 403 error, were you able to resolve this? 

2. Regarding the HTTPS warning, the plug-in loads all dependencies with relative URL's so there might be something up with your installation if its not loading that JS file over HTTPS.

**Comment by mattmintun** [comment]
This should be fixed in the most recent release of Groups.
